name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Validate using XSDs
      uses: klakegg/xsdchecker@master
      with:
        script: |
          wget -q -O Moribus-2.xsd \
            https://github.com/anskaffelser/vefa-moribus/releases/download/v0.9.0/Moribus-2.xsd
          xc Moribus-2.xsd $(find moribus -type f -name *.xml | sort)

    - name: Run Moribus
      uses: anskaffelser/vefa-moribus@v0.9.0
